### PR TITLE
Fix find_symmertry utility

### LINKED ISSUE #273: bug in find_symmetry utility
I just tried using the find_symmetry utility (input: `viperleed poscar find_symmetry < POSCAR`) and get the following error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\fkrau\anaconda3\envs\viperleed\Scripts\viperleed.exe\__main__.py", line 7, in <module>
  File "C:\Users\fkrau\anaconda3\envs\viperleed\Lib\site-packages\viperleed\cli_base.py", line 423, in run_as_script
    exit_code = cli()
                ^^^^^
  File "C:\Users\fkrau\anaconda3\envs\viperleed\Lib\site-packages\viperleed\cli_base.py", line 256, in __call__
    return command(args)
           ^^^^^^^^^^^^^
  File "C:\Users\fkrau\anaconda3\envs\viperleed\Lib\site-packages\viperleed\utilities\poscar\base.py", line 45, in __call__
    slab = self.read_poscar(parsed_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fkrau\anaconda3\envs\viperleed\Lib\site-packages\viperleed\utilities\poscar\base.py", line 194, in read_poscar
    raise AttributeError('--infile argument is missing. If you have '
AttributeError: --infile argument is missing. If you have overridden add_parser_arguments without also overriding read_poscar, make sure to call add_infile_argument in your overridden add_parser_arguments
```

This is with the current version of the master branch (i.e. recently installed with `pip install viperleed`). Environment is Windows, and Python 3.12.7 (using Anaconda).

I briefly tested `delete_above` to see whether this is a more general problem with the POSCAR utilities, but that one works fine.

Probably something for @amimre?

### PR DESCRIPTION
**Pull request by michele-riva**
Fixes #273

### CODE REVIEW

**Comment by michele-riva** [comment]
Quick testing showed that these changes indeed fix the original problem in #273.

@fkraushofer: could you try out whether this indeed works as expected now?
@amimre: would you be so kind to write a few tests for full coverage of these poscar symmertry utilities?

**Comment by michele-riva** [comment]
One more question for both: I now have --symmetry-eps (and related argument) come later in the list of CLI arguments than all the others. It was a 50/50 choice. Would you prefer to have them earlier (before `-i`, `-o`, and `-v`)? This only concerns the way the arguments are shown in `--help`, as they all are optional, so they can be given in whatever order in the terminal.

**Comment by amimre** [comment]
I would show the arguments relevant to the concrete utility at the top, but I think it's a very minor style issue.

**Comment by amimre** [comment]
I've added the test for the find symmetry utility. @michele-riva is there a more elegant way than having to manually close the outfile wrapper as I do on L47?

**Comment by michele-riva** [comment]
> I've added the test for the find symmetry utility. @michele-riva is there a more elegant way than having to manually close the outfile wrapper as I do on L47?

Thanks for adding the tests, I'll have a look at L47 and see if there's another option.

**Comment by amimre** [comment]
@michele-riva the `*_to_outfile` and `*_to_stdout` test are failing for me with an IO exception. Could you double-check?

**Comment by michele-riva** [comment]
> @michele-riva the `*_to_outfile` and `*_to_stdout` test are failing for me with an IO exception. Could you double-check?

Funny. They seem working fine for me. I'll come up in a minute.

**Comment by michele-riva** [comment]
@amimre: could you try whether 508b6f9 fixed it?

**Comment by amimre** [comment]
> @amimre: could you try whether [508b6f9](https://github.com/viperleed/viperleed/commit/508b6f9f268e28aab5e75d5ba13c5b11f799f26c) fixed it?

Yes, that did the trick

**Review by amimre — APPROVED** [review]

**Pull request merged**
