### PR TITLE
v0.12.2

### PR DESCRIPTION
**Pull request by amimre**
Merge v0.12.2 into master for release.
Contains various bug fixes.

### CODE REVIEW

**Comment by amimre** [comment]
I just ran the whole test suite on 3.8:
42 failed, 6046 passed, 261 skipped, 260 xfailed, 2 xpassed, 30 errors, 3535 subtests passed in 13229.99s (3:40:29)
Not sure though, which tests were failing before already.

**Comment by michele-riva** [comment]
Hmm the last time I checked there were zero failures on my machine (xfail is OK). Perhaps let's check tomorrow what is failing.

**Comment by amimre** [comment]
Sounds good. I'll run the suite on v0.12.1 overnight to check what is actually broken, and what is just my setup.

**Comment by michele-riva** [comment]
Perfect. It would be good to create a list of failures (e.g., in a text file) so we can look more in detail on what are the problems.

**Comment by amimre** [comment]
Seems like the same tests are failing for me on v0.12.1 so it's likely just due to my personal setup and not related to changes in v0.12.2.

**Comment by michele-riva** [comment]
After a check with @amimre, the problem was indeed a misconfiguration of his environment where VIPERLEED_TENSORLEED was pointing to a folder containing a TensErLEED v1.6.1. This, however, uncovered some issues with the tests, as well as with `get_tensorleed_path`, which I will fix now.

**Comment by michele-riva** [comment]
beamgen tests: #282

Concerning this:
> [...] as well as with `get_tensorleed_path`, which I will fix now.

After a check of the current layout of the [viperleed-tensorleed](https://github.com/viperleed/viperleed-tensorleed) repository, I don't think we need any changes to `get_tensorleed_path`.

**Comment by amimre** [comment]
We'll just quickly include #231 in here before merging to master.

**Comment by michele-riva** [comment]
Perhaps let's also merge #282 after @amimre's review

**Review by michele-riva — DISMISSED** [review]
Good to go from my point of view!

**Review by michele-riva — APPROVED** [review]

**Comment by michele-riva** [comment]
I've also edited the release draft. It is good to go from my perspective. Please check again that the "target" for the release is indeed correct. It feels like it should actually be "master" as soon as this PR is merged.

**Pull request merged**
